import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { useRouter } from 'expo-router';
import { useTranslation } from 'react-i18next';
import { Feather } from '@expo/vector-icons';
import { colors } from '../constants/theme';

export default function PrivacyScreen() {
  const { t } = useTranslation();
  const router = useRouter();

  return (
    <View style={styles.root}>
      <View style={styles.header}>
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 16, marginBottom: 16 }}>
          <TouchableOpacity onPress={() => router.back()} style={{ padding: 8 }}>
            <Feather name="arrow-left" size={22} color={colors.white} />
          </TouchableOpacity>
          <Text style={{ fontSize: 20, fontWeight: '800', color: colors.white }}>{t('privacy.title')}</Text>
        </View>
      </View>
      <ScrollView style={styles.body} contentContainerStyle={styles.bodyContent}>
        <Text style={styles.sectionTitle}>1. Who We Are</Text>
        <Text style={styles.text}>Tenachin AI is an app built for Ethiopian patients living with Type 2 diabetes. This policy explains what the app collects, why we collect it, how it is stored and shared, and the rights you have over your own data. For any privacy question, email hello@tenachinai.site.</Text>

        <Text style={styles.sectionTitle}>2. Information We Collect</Text>
        <Text style={styles.text}>Information you give us: your name and basic profile details, your diabetes information (such as diagnosis details and current medication list), and the glucose readings, symptoms, medication logs, and appointment dates you record in the app.</Text>
        <Text style={styles.text}>We do not collect your phone contacts, location, or files unless you choose to add them yourself. We do not sell, rent, or trade your data to anyone.</Text>

        <Text style={styles.sectionTitle}>3. How We Use Your Information</Text>
        <Text style={styles.text}>To display your glucose history, trends, and adherence statistics back to you. To generate your personalized daily AI tip based on your own readings and habits. To send you reminders (medication and appointments) and one-time security codes by email. To generate the PDF report you export for your doctor's visit.</Text>

        <Text style={styles.sectionTitle}>4. Artificial Intelligence Tips</Text>
        <Text style={styles.text}>Your daily tips are generated by an AI model. Only the data needed to write a relevant tip (for example, recent glucose readings and medication adherence) is sent to our AI provider. This data is processed transiently, is not used to train their models, and is not sold.</Text>
        <Text style={styles.text}>Tenachin AI gives information and encouragement only. It does not diagnose, prescribe, or change your medication doses. Always follow the advice of your treating clinician.</Text>

        <Text style={styles.sectionTitle}>5. Storage, Security, and Processors</Text>
        <Text style={styles.text}>Your data is stored on secured infrastructure, protected with encryption in transit (TLS) and at rest, and is also saved on your own device first and synced when you are back online.</Text>
        <Text style={styles.text}>To run the service, limited data passes through these third parties: Resend (sends your email confirmations and one-time codes), Groq (generates your AI daily tips), and Cloudflare R2 (object storage for backups and generated files). Each is bound to use the data only to provide the service we rely on.</Text>

        <Text style={styles.sectionTitle}>6. Data Retention</Text>
        <Text style={styles.text}>We keep your account and health data for as long as your account is active. If you ask us to delete your account, we will remove your personal data. Backup copies may persist for a limited period before being automatically purged.</Text>

        <Text style={styles.sectionTitle}>7. Your Rights</Text>
        <Text style={styles.text}>Access: request a copy of the data we hold about you. Export: take your data with you, including the PDF reports the app generates. Correct: update or fix inaccurate information. Delete: request deletion of your account and data.</Text>
        <Text style={styles.text}>To exercise any of these rights, email hello@tenachinai.site. We respond within 30 days. You can also delete your account from the profile settings.</Text>

        <Text style={styles.sectionTitle}>8. Children</Text>
        <Text style={styles.text}>Tenachin AI is intended for adults aged 18 and older. It is not designed for children under 13, and we do not knowingly collect information from children.</Text>

        <Text style={styles.sectionTitle}>9. Changes to This Policy</Text>
        <Text style={styles.text}>If we make material changes, we will update the "Last updated" date and, where practical, notify you in the app. Continued use of the app after changes means you accept the updated policy.</Text>

        <Text style={styles.sectionTitle}>10. Contact</Text>
        <Text style={styles.text}>Questions about this policy or your data? Email hello@tenachinai.site.</Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  header: {
    backgroundColor: colors.green,
    paddingTop: 52,
    paddingBottom: 20,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  body: { flex: 1 },
  bodyContent: { padding: 24, paddingBottom: 48 },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.t1,
    marginTop: 24,
    marginBottom: 8,
  },
  text: {
    fontSize: 14,
    color: colors.t2,
    lineHeight: 22,
  },
});
